Repository VitorBSP/Tempo_Tela, pull requests merged in 2022-02, with the labels that each got.

#2 first commit
  relatorio.Rmd
  relatorio.log
  relatorio.pdf
Labels: enhancement

#3 Renata e Carol works
  relatorio.Rmd
  relatorio.log
  relatorio.out
  relatorio.pdf
  relatorio.toc
Labels: enhancement

#5 boa revisao
  relatorio.Rmd
  relatorio.log
  relatorio.out
  relatorio.pdf
  relatorio.toc
Labels: help wanted

#6 corrigir
  relatorio.Rmd
  relatorio.log
  relatorio.out
  relatorio.pdf
  relatorio.toc
Labels: enhancement, question

#7 fim
  relatorio.Rmd
  relatorio.log
  relatorio.pdf
  relatorio.toc
Labels: documentation
